language:
    - node_js
node_js:
    - stable
env:
  global:
    - CXX=g++-5
    - NODE_ENV=test

before_install:
  - npm install -g node-gyp node-pre-gyp

before_script:
  - psql -c "CREATE DATABASE book_a_meal_test;" -U postgres
  - psql -c "CREATE USER hasstrupezekiel WITH PASSWORD 'PASSWORD';" -U postgres

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

services:
  - postgresql

after_success:
    - npm run cover

deploy:
  provider: heroku
  api_key: 
    secure: 9af2e9f0-20d0-49ed-a70b-398ee1538e93
  app: my-book-a-meal-app
  on:
    repo: Hasstrup/book-a-meal
    branch: develop