language:
    - node_js
node_js:
    - stable
env:
  global:
    - CXX=g++-5
    - NODE_ENV=test

before_install:
  - npm install -g node-gyp node-pre-gyp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

services:
  - postgresql

after_success:
    - npm run cover
