language:
    - node_js
node_js:
    - stable
env:
  global:
    - CC_TEST_REPORTER_ID=1c4feae9a685078726b61358fc7145f29761f877f1a8e5f2538d593dea207a89
    - CXX=g++-5
    - NODE_ENV=test

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

services:
  - postgresql

before_install:
  - npm install -g node-gyp node-pre-gyp

after_success:
    - npm run cover
