language: node_js
node_js:
  - "stable"
  after_script:
    - "npm run coverage"
    - "CODECLIMATE_REPO_TOKEN=31ab9bd61c1a98bd654d10c26f1ec24b5ae2af6939190a3d14660784bd3eecd4 codeclimate-test-reporter < ./coverage/lcov.info"
